### PR TITLE
feature: Generate documentation in CI CY-3654

### PR DESCRIPTION
**Pull request by franciscodua**

### CODE REVIEW

**Comment by lolgab** [comment]
Why you needed to remove the multistage `Dockerfile`?

**Comment by franciscodua** [comment]
> Why you needed to remove the multistage `Dockerfile`?

This tool used a strange flow to generate the docker image.
It needed to build an image with cppcheck. Then, it used that image to generate some information used for the doc generation. Finally, the docs generated in the last step were used to create the final image.

Since this was a bit of a loop. I separated the base part to a different file "Dockerfile.base". Now, we can use this base file to generate the docs, and later to generate the Docker image, without having to create it multiple times.

**Comment by lolgab** [comment]
You can achieve this without moving the parts away, using the `--target base` to build the image so the build stops a the `base` stage. I would avoid having so many `Dockerfile`s

**Comment by franciscodua** [comment]
> You can achieve this without moving the parts away, using the --target base to build the image so the build stops a the base stage. I would avoid having so many Dockerfiles

Won't this makes us build the base image twice? One to generate the docs (with the `--target base`) and the other when we build the final image?

**Comment by lolgab** [comment]
> Won't this makes us build the base image twice? One to generate the docs (with the `--target base`) and the other when we build the final image?

If you generate it in the same machine I guess the first image will be re-used as a layer of the second image

**Review by lolgab — APPROVED** [review]
Was hard but you made it 🎉🎉

**Pull request merged**
